INSERT INTO movies (name, description, poster_path, rating, status, created_at, updated_at) VALUES ('El padrino','La saga de la familia criminal Corleone y el ascenso de Michael Corleone al liderazgo de la mafia.', 'https://w7.pngwing.com/pngs/537/503/png-transparent-the-godfather-logo-never-give-up-text-monochrome-black-thumbnail.png', 8.4, 'publicada', NOW(), NOW());

INSERT INTO movies (name, description, poster_path, rating, status, created_at, updated_at) VALUES ('Sueño de Fuga','Dos hombres encarcelados se unen a lo largo de varios años, encontrando consuelo y redención mediante actos de decencia común.', 'https://m.media-amazon.com/images/M/MV5BMzdhNGE2ZjAtYjFjYS00YmY2LTg4MDctZTNhN2VlOGM3NjUwXkEyXkFqcGc@._V1_.jpg', 9.3, 'publicada', NOW() - INTERVAL '2 years 3 months', NOW() - INTERVAL '3 months');

INSERT INTO movies (name, description, poster_path, rating, status, created_at, updated_at) VALUES ('Cadena Perpetua','Un ex convicto regresa a un club de lucha subterráneo, creando una organización nacional con reglas estrictas.','https://m.media-amazon.com/images/M/MV5BMTA1MjE0Nzk4MDleQTJeQWpwZ15BbWU4MDA0NjIxMjAx._V1_FMjpg_UX1000_.jpg',8.8,'edicion',NOW() - INTERVAL '1 month', NOW() - INTERVAL '1 month');

INSERT INTO movies (name, description, poster_path, rating, status, created_at, updated_at) VALUES ('Forrest Gump', 'La vida y aventuras de un hombre con un bajo coeficiente intelectual que es testigo de varios momentos históricos.', 'https://wallpapers.com/images/featured/forrest-gump-t7fimpldrjxqk3ns.jpg', 8.5,'publicada', NOW() - INTERVAL '10 months', NOW() - INTERVAL '5 months');

INSERT INTO movies (name, description, poster_path, rating, status, created_at, updated_at) VALUES ('Matrix','Un programador de computadoras descubre que la realidad que conoce es un engaño creado por máquinas.','https://m.media-amazon.com/images/M/MV5BNGE1YzI4NzMtZTUxNi00Y2I5LTg2MmQtODE0NThmYTFmMDk0XkEyXkFqcGc@._V1_.jpg', 8.7, 'edicion', NOW() - INTERVAL '4 years', NOW() - INTERVAL '2 years');
