eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: movies
          uri: http://localhost:8090
          predicates:
            - Path=/api/movies/**